/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Equipo
 */
public class VistaONG extends javax.swing.JFrame {

    /**
     * Creates new form VistaONG
     */
    public VistaONG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSubsidioOtorgado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValorAPagar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtPromedio = new javax.swing.JTextField();
        txtValorSemestre = new javax.swing.JTextField();
        lblSubsidio80 = new javax.swing.JLabel();
        lblSubsidio60 = new javax.swing.JLabel();
        lblSubsidio20 = new javax.swing.JLabel();
        lblSubsidio40 = new javax.swing.JLabel();
        lblPorcentaje60 = new javax.swing.JLabel();
        lblPorcentaje80 = new javax.swing.JLabel();
        lblCantidadEstudiantesAfiliados = new javax.swing.JLabel();
        lblEstudiantesSinSubsidio = new javax.swing.JLabel();
        lblcantidadal60 = new javax.swing.JLabel();
        lblcantidadal80 = new javax.swing.JLabel();
        lblTotalDineroDonado = new javax.swing.JLabel();
        lblPorcentaje20 = new javax.swing.JLabel();
        lblPorcentaje40 = new javax.swing.JLabel();
        lblcantidadal40 = new javax.swing.JLabel();
        lblcantidadal20 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        lblcantidadTotalDeEstudiantes = new javax.swing.JLabel();

        setTitle("ONG \"LA BENDICIÓN\"");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("SUBSIDIOS ONG \"LA BENDICIÓN\"");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRES");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel3.setText("APELLIDOS");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setText("VALOR SEMESTRE");

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setText("PROMEDIO");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel6.setText("SUBSIDIO:");

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel7.setText("VALOR A PAGAR:");

        lblSubsidioOtorgado.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lblSubsidioOtorgado.setForeground(new java.awt.Color(255, 0, 51));
        lblSubsidioOtorgado.setText("................................");

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel9.setText("Estudiantes con subsidio del 80%: ");

        lblValorAPagar.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lblValorAPagar.setForeground(new java.awt.Color(255, 0, 51));
        lblValorAPagar.setText("................................");

        jLabel11.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel11.setText("Estudiantes con subsidio del 60%: ");

        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel12.setText("Estudiantes con subsidio del 20%: ");

        jLabel13.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel13.setText("Estudiantes con subsidio del 40%: ");

        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel14.setText("Estudiantes SIN subsidio:");

        jLabel15.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel15.setText("Dinero donado en subsidio del 80% por la ONG \"LA BENDICIÓN\":");

        jLabel16.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel16.setText("Estudiantes afiliados a la ONG \"LA BENDICIÓN\":");

        jLabel17.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel17.setText("Dinero donado en subsidio del 60% por la ONG \"LA BENDICIÓN\":");

        jLabel18.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel18.setText("Dinero donado en subsidio del 20% por la ONG \"LA BENDICIÓN\":");

        jLabel19.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel19.setText("Dinero donado en subsidio del 40% por la ONG \"LA BENDICIÓN\":");

        jLabel20.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel20.setText("Total dinero donado por la ONG \"LA BENDICIÓN\":");

        jLabel21.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel21.setText("Porcentaje de estudiantes con subsidio del 80%: ");

        jLabel22.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel22.setText("Porcentaje de estudiantes con subsidio del 60%: ");

        jLabel23.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel23.setText("Porcentaje de estudiantes con subsidio del 20%: ");

        jLabel24.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel24.setText("Porcentaje de estudiantes con subsidio del 40%: ");

        txtNombres.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N

        txtApellidos.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N

        txtPromedio.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N

        txtValorSemestre.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N

        lblSubsidio80.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblSubsidio80.setForeground(new java.awt.Color(255, 0, 51));
        lblSubsidio80.setText(".................................");

        lblSubsidio60.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblSubsidio60.setForeground(new java.awt.Color(255, 0, 51));
        lblSubsidio60.setText("................................");

        lblSubsidio20.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblSubsidio20.setForeground(new java.awt.Color(255, 0, 51));
        lblSubsidio20.setText("................................");

        lblSubsidio40.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblSubsidio40.setForeground(new java.awt.Color(255, 0, 51));
        lblSubsidio40.setText("................................");

        lblPorcentaje60.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblPorcentaje60.setForeground(new java.awt.Color(255, 0, 51));
        lblPorcentaje60.setText("................................");

        lblPorcentaje80.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblPorcentaje80.setForeground(new java.awt.Color(255, 0, 51));
        lblPorcentaje80.setText("................................");

        lblCantidadEstudiantesAfiliados.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblCantidadEstudiantesAfiliados.setForeground(new java.awt.Color(255, 0, 51));
        lblCantidadEstudiantesAfiliados.setText("................................");

        lblEstudiantesSinSubsidio.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblEstudiantesSinSubsidio.setForeground(new java.awt.Color(255, 0, 51));
        lblEstudiantesSinSubsidio.setText("................................");

        lblcantidadal60.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblcantidadal60.setForeground(new java.awt.Color(255, 0, 51));
        lblcantidadal60.setText("................................");

        lblcantidadal80.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblcantidadal80.setForeground(new java.awt.Color(255, 0, 51));
        lblcantidadal80.setText("................................");

        lblTotalDineroDonado.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblTotalDineroDonado.setForeground(new java.awt.Color(255, 0, 51));
        lblTotalDineroDonado.setText("................................");

        lblPorcentaje20.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblPorcentaje20.setForeground(new java.awt.Color(255, 0, 51));
        lblPorcentaje20.setText("................................");

        lblPorcentaje40.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblPorcentaje40.setForeground(new java.awt.Color(255, 0, 51));
        lblPorcentaje40.setText("................................");

        lblcantidadal40.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblcantidadal40.setForeground(new java.awt.Color(255, 0, 51));
        lblcantidadal40.setText("................................");

        lblcantidadal20.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblcantidadal20.setForeground(new java.awt.Color(255, 0, 51));
        lblcantidadal20.setText("................................");

        btnCalcular.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setEnabled(false);

        btnGuardar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");

        btnNuevo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setEnabled(false);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setEnabled(false);

        btnSalir.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel25.setText("TOTAL DE ESTUDIANTES:");

        lblcantidadTotalDeEstudiantes.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        lblcantidadTotalDeEstudiantes.setForeground(new java.awt.Color(255, 0, 51));
        lblcantidadTotalDeEstudiantes.setText("................................");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(77, 77, 77))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtApellidos)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSubsidioOtorgado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(519, 519, 519)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblcantidadTotalDeEstudiantes)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblcantidadal40)
                                                    .addComponent(lblcantidadal20)
                                                    .addComponent(lblcantidadal80)
                                                    .addComponent(lblcantidadal60)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblSubsidio60)
                                                        .addComponent(lblSubsidio40)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblSubsidio20)
                                                            .addComponent(lblSubsidio80))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblValorAPagar)))
                                .addGap(182, 182, 182))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalDineroDonado)
                            .addComponent(lblEstudiantesSinSubsidio)
                            .addComponent(lblCantidadEstudiantesAfiliados)
                            .addComponent(lblPorcentaje80)
                            .addComponent(lblPorcentaje60)
                            .addComponent(lblPorcentaje40)
                            .addComponent(lblPorcentaje20))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lblSubsidioOtorgado)
                    .addComponent(lblValorAPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo)
                        .addGap(6, 6, 6)
                        .addComponent(btnSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel13)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(lblcantidadal40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblcantidadal20))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblcantidadal80)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblcantidadal60))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lblcantidadTotalDeEstudiantes))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblEstudiantesSinSubsidio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblCantidadEstudiantesAfiliados))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSubsidio80)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSubsidio60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSubsidio40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSubsidio20)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblTotalDineroDonado))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPorcentaje80)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPorcentaje60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPorcentaje40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPorcentaje20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblCantidadEstudiantesAfiliados;
    public javax.swing.JLabel lblEstudiantesSinSubsidio;
    public javax.swing.JLabel lblPorcentaje20;
    public javax.swing.JLabel lblPorcentaje40;
    public javax.swing.JLabel lblPorcentaje60;
    public javax.swing.JLabel lblPorcentaje80;
    public javax.swing.JLabel lblSubsidio20;
    public javax.swing.JLabel lblSubsidio40;
    public javax.swing.JLabel lblSubsidio60;
    public javax.swing.JLabel lblSubsidio80;
    public javax.swing.JLabel lblSubsidioOtorgado;
    public javax.swing.JLabel lblTotalDineroDonado;
    public javax.swing.JLabel lblValorAPagar;
    public javax.swing.JLabel lblcantidadTotalDeEstudiantes;
    public javax.swing.JLabel lblcantidadal20;
    public javax.swing.JLabel lblcantidadal40;
    public javax.swing.JLabel lblcantidadal60;
    public javax.swing.JLabel lblcantidadal80;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtPromedio;
    public javax.swing.JTextField txtValorSemestre;
    // End of variables declaration//GEN-END:variables
}
